language: php

php:
  - 5.3.2

env:
  - SYMFONY_VERSION=v2.0.12
  - SYMFONY_VERSION=origin/master

before_script:
  - php Tests/vendors.php.dist

notifications:
  email:
    - gdeveloperaccount@gmail.com
