language: php

php:
  - 5.3.2

before_script:
  - mkdir -p src/MQM/Bundle/PaginationBundle  
  - ls -1 | grep -v "^src" | xargs -n 1 -i./ mv ./ src/MQM/Bundle/PaginationBundle
  - git clone https://github.com/symfony/symfony-standard.git symfony
  - cp -ap symfony/* ./
  - rm -rf symfony
  - pyrus install phpunit/DbUnit
  - mkdir -p app/cache app/logs
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - php app/console doctrine:database:create

script: "phpunit -c app"

notifications:
  email:
    on_failure: always
    on_success: change